working on android build

diff --git a/Dockerfile.android b/Dockerfile.android
--- a/Dockerfile.android
+++ b/Dockerfile.android
@@ -22,43 +22,68 @@ RUN cd SDL/build-scripts && \
     PATH=$PATH:/android-ndk-r27c ./androidbuildlibs.sh
 
 # Create Android project with an empty main.cpp to cache the gradle download step
-RUN mkdir -p /number_sequence_game/src && \
-    touch /number_sequence_game/src/main.cpp && \
+RUN mkdir -p /abc_speak/src && \
+    touch /abc_speak/src/main.cpp && \
     cd /SDL/build-scripts && \
-    ./create-android-project.py org.libsdl.number_sequence_game /number_sequence_game/src/main.cpp
+    ./create-android-project.py org.libsdl.abc_speak /abc_speak/src/main.cpp
 
 # Build the empty project to get everything in place
-RUN cd /SDL/build/org.libsdl.number_sequence_game && \
-    ANDROID_HOME=/android-sdk ANDROID_NDK_HOME=android-ndk-r27c ./gradlew assembleDebug
+RUN cd /SDL/build/org.libsdl.abc_speak && \
+    ANDROID_HOME=/android-sdk ANDROID_NDK_HOME=/android-ndk-r27c ./gradlew assembleDebug
 
 # GLM is header only
 RUN cd / && git clone -b 1.0.1 --depth 1 https://github.com/g-truc/glm.git
-RUN cd /SDL/build/org.libsdl.number_sequence_game/app/jni/src && \
+RUN cd /SDL/build/org.libsdl.abc_speak/app/jni/src && \
     ln -s /glm/glm .
 
 # Enable C++ STL
-RUN cd /SDL/build/org.libsdl.number_sequence_game/app/jni && \
+RUN cd /SDL/build/org.libsdl.abc_speak/app/jni && \
     sed -i 's/# APP_STL/APP_STL/g' Application.mk
 
 # Enable C++20
-RUN cd /SDL/build/org.libsdl.number_sequence_game/app/jni/src && \
+RUN cd /SDL/build/org.libsdl.abc_speak/app/jni/src && \
     echo 'set(CMAKE_CXX_STANDARD 20)' >> CMakeLists.txt && \
-    echo 'APP_CPPFLAGS := -std=c++20' >> /SDL/build/org.libsdl.number_sequence_game/app/jni/Application.mk
+    echo 'APP_CPPFLAGS := -std=c++20' >> /SDL/build/org.libsdl.abc_speak/app/jni/Application.mk
 
-# Enable x86_64 build for debugging on the emulator
-# RUN cd /SDL/build/org.libsdl.number_sequence_game/app && \
-    # sed -i "s/abiFilters 'arm64-v8a'/abiFilters 'arm64-v8a','x86_64'/g" build.gradle
+# Workaround for build error following vosk official instruction.
+# NDK r27c has stricter compiler warnings by default that causes compiling failure.
+# The workaround is to upgrade OpenBlas to 0.3.28 and enable the __EMSCRIPTEN__ define.
+RUN apt-get -y install autoconf libtool
+RUN git clone https://github.com/alphacep/vosk-api.git
+RUN cd vosk-api/android/lib && \
+    git checkout cf67ed6 && \
+    sed -i '27s/set -x/set -ex/g' build-vosk.sh && \
+    sed -i '82s/v0.3.20/v0.3.28/g' build-vosk.sh && \
+    sed -i '35s/armeabi-v7a arm64-v8a x86_64 x86/arm64-v8a/g' build-vosk.sh && \
+    sed -i '114s/-O3/-O3 -D__EMSCRIPTEN__/g' build-vosk.sh && \
+    ANDROID_HOME=/android-sdk ANDROID_NDK_HOME=/android-ndk-r27c ./build-vosk.sh 
 
-RUN rm -rf /SDL/build/org.libsdl.number_sequence_game/app/src/main/res/
+RUN cd vosk-api/android/lib && \
+    sed -i '14d' build.gradle && \
+    sed -i '19i    ndkPath "/android-ndk-r27c"' build.gradle && \
+    ANDROID_HOME=/android-sdk `find /root/.gradle/wrapper -name gradle` build
+
+RUN cp /vosk-api/android/lib/build/kaldi_arm64-v8a/vosk/libvosk.so /SDL/build/org.libsdl.abc_speak/app/jni/src
+
+# RUN wget https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip && \
+    # unzip vosk-model-small-en-us-0.15.zip
+
+# Enable x86_64 build for debugging on the emulator. Don't forget to build x86_64 version of Vosk as well.
+# RUN cd /SDL/build/org.libsdl.abc_speak/app && \
+# sed -i "s/abiFilters 'arm64-v8a'/abiFilters 'arm64-v8a','x86_64'/g" build.gradle
+
+RUN rm -rf /SDL/build/org.libsdl.abc_speak/app/src/main/res/
 
 # Build our actual project
-COPY src /SDL/build/org.libsdl.number_sequence_game/app/jni/src/
-COPY assets /SDL/build/org.libsdl.number_sequence_game/app/src/main/assets/
-COPY android/Android.mk /SDL/build/org.libsdl.number_sequence_game/app/jni/src
-COPY android/AndroidManifest.xml /SDL/build/org.libsdl.number_sequence_game/app/src/main
-COPY android/res/ /SDL/build/org.libsdl.number_sequence_game/app/src/main/res/
+COPY src /SDL/build/org.libsdl.abc_speak/app/jni/src/
+COPY assets /SDL/build/org.libsdl.abc_speak/app/src/main/assets/
+COPY android/Android.mk /SDL/build/org.libsdl.abc_speak/app/jni/src
+COPY android/AndroidManifest.xml /SDL/build/org.libsdl.abc_speak/app/src/main
+COPY android/res/ /SDL/build/org.libsdl.abc_speak/app/src/main/res/
 
-RUN cd /SDL/build/org.libsdl.number_sequence_game && \
+# RUN mv /vosk-model-small-en-us-0.15 /SDL/build/org.libsdl.abc_speak/app/src/main/assets/
+
+RUN cd /SDL/build/org.libsdl.abc_speak && \
     ANDROID_HOME=/android-sdk ANDROID_NDK_HOME=/android-ndk-r27c ./gradlew assembleDebug
 
-CMD ["/usr/bin/python3", "-m", "http.server", "--directory", "/SDL/build/org.libsdl.number_sequence_game/app/build/outputs/apk/debug"]
+CMD ["/usr/bin/python3", "-m", "http.server", "--directory", "/SDL/build/org.libsdl.abc_speak/app/build/outputs/apk/debug"]
